.TH VALKEY-CLI 1 "January 13, 2010"
.SH NAME
valkey-cli \- Command-line client to valkey-server
.SH SYNOPSIS
.B valkey-cli
.RI [options]
.SH DESCRIPTION
Valkey is a key-value database. It is similar to memcached but the dataset is
not volatile and other datatypes (such as lists and sets) are natively
supported.
.PP
\fBvalkey-cli\fP provides a simple command-line interface to a Valkey server.
.SH OPTIONS
See \fBvalkey-doc\fP for more information on the commands Valkey accepts.
.SH AUTHOR
\fBvalkey-cli\fP was written by Salvatore Sanfilippo.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
