.TH VALKEY-CHECK-AOF 1 "December 13, 2018"
.SH NAME
valkey-check-aof \- Check integrity of a Valkey .AOF file
.SH SYNOPSIS
.B valkey-check-aof
filename
.SH DESCRIPTION
Valkey is a key-value database. It is similar to memcached but the dataset is
not volatile and other datatypes (such as lists and sets) are natively
supported.
.PP
This utility checks the integrity of a dumped .AOF file.
.SH AUTHOR
\fBvalkey-check-aof\fP was written by Salvatore Sanfilippo.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
