name: Builds Linux X86 binary packages into S3 bucket.

on:
  workflow_call:
    inputs:
      version:
        description: The version of Valkey to create.
        type: string
        required: true
      build_matrix:
        description: The build targets to produce as a JSON matrix.
        type: string
        required: true
      region:
        description: The AWS region to upload the packages to.
        type: string
        required: true
    secrets:
      bucket_name:
        description: The name of the S3 bucket to upload the packages to.
        required: true
      role_to_assume:
        description: The role to assume for the S3 bucket.
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test-valkey:
    # Capture source tarball and generate checksum for it
    name: Build and test package ${{ matrix.distro.target }} ${{ matrix.distro.arch }}
    runs-on: ${{ matrix.distro.target }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.build_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ github.repository_owner }}/valkey
          ref: ${{ inputs.version }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libsystemd-dev tcl tcl-tls python3 bc curl

      - name: Make Valkey
        run: |
          set -euo pipefail
          
          VERSION="${{ inputs.version }}"
          echo "Building for version: $VERSION"

          make -C deps

          if [[ "$VERSION" != "unstable" ]]; then
            MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
            if [[ $(echo "$MAJOR_MINOR < 8.1" | bc -l) -eq 1 ]]; then
              echo "Version $MAJOR_MINOR is less than 8.1 — no USE_FAST_FLOAT"
              make -C src all BUILD_TLS=yes USE_SYSTEMD=yes
            else
              echo "Version $MAJOR_MINOR is 8.1 or higher — enabling USE_FAST_FLOAT"
              make -C src all BUILD_TLS=yes USE_SYSTEMD=yes USE_FAST_FLOAT=yes
            fi
          else
            echo "Unstable version detected — enabling USE_FAST_FLOAT"
            make -C src all BUILD_TLS=yes USE_SYSTEMD=yes USE_FAST_FLOAT=yes
          fi

      - name: Run Valkey test suite
        run: ./runtest
      
      - name: Create Tarball and SHA256sums
        run: |
          TAR_FILE_NAME=valkey-${{inputs.version}}-${{matrix.distro.platform}}-${{ matrix.distro.arch}}
          mkdir -p "$TAR_FILE_NAME/bin" "$TAR_FILE_NAME/share"
          rsync -av --exclude='*.c' --exclude='*.d' --exclude='*.o' src/valkey-* "$TAR_FILE_NAME/bin/"
          cp -v COPYING "$TAR_FILE_NAME/share/LICENSE"
          tar -czvf $TAR_FILE_NAME.tar.gz $TAR_FILE_NAME
          sha256sum $TAR_FILE_NAME.tar.gz > $TAR_FILE_NAME.tar.gz.sha256
          mkdir -p packages-files
          cp -rfv $TAR_FILE_NAME.tar* packages-files/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.role_to_assume }}

      - name: Sync to S3
        run: aws s3 sync packages-files s3://${{ secrets.bucket_name }}/releases/